#!/usr/bin/env ruby

require "bundler/setup"

require "foobara/load_dotenv"
Foobara::LoadDotenv.run!(dir: __dir__)

require "foobara/remote_imports"

Foobara::RemoteImports::ImportCommand.run!(
  manifest_url: "https://app.commandforge.com/manifest",
  to_import: "Foobara::Commandforge::CreateType",
  auth_header: ["x-api-key", -> { ENV.fetch("COMMANDFORGE_API_KEY") }],
  cache: false
)

Foobara::Commandforge::CreateType.run!(
  organization_name: "SfRuby",
  domain_name: "AngelListMeetupDemos",
  type_name: :language,
  type_declaration: <<~HERE
    ---
    :one_of:
    - English
    - Spanish
    :type: :string
  HERE
)

Foobara::Commandforge::CreateType.run!(
  organization_name: "SfRuby",
  domain_name: "AngelListMeetupDemos",
  type_name: :AnalyzedNoun,
  type_declaration: <<~HERE
    ---
    :type: :model
    :name: AnalyzedNoun
    :model_module: SfRuby::AngelListMeetupDemos
    :model_class: SfRuby::AngelListMeetupDemos::AnalyzedNoun
    :model_base_class: Foobara::Model
    :attributes_declaration:
      :type: :attributes
      :element_type_declarations:
        :noun:
          :description: the original, uninflected noun
          :type: :string
        :language:
          :description: the language of the noun
          :type: :SfRuby::AngelListMeetupDemos::language
        :uninflected:
          :description: the uninflected form of the noun
          :type: :string
      :required:
      - :language
      - :noun
      - :uninflected
  HERE
)
Foobara::Commandforge::CreateType.run!(
  organization_name: "SfRuby",
  domain_name: "AngelListMeetupDemos",
  type_name: :AnalyzedVerb,
  type_declaration: <<~HERE
    ---
    :type: :model
    :name: AnalyzedVerb
    :model_module: SfRuby::AngelListMeetupDemos
    :model_class: SfRuby::AngelListMeetupDemos::AnalyzedVerb
    :model_base_class: Foobara::Model
    :attributes_declaration:
      :type: :attributes
      :element_type_declarations:
        :verb:
          :description: "the original, uninflected verb, spell-corrected if necessary"
          :type: :string
        :language:
          :description: the language of the verb
          :type: :SfRuby::AngelListMeetupDemos::language
        :uninflected:
          :description: the uninflected form of the verb
          :type: :string
        :subject:
          :allow_nil: true
          :description: the noun that is the subject of the verb if there is one
          :type: :string
        :direct_object:
          :allow_nil: true
          :description: the noun that is the direct object of the verb if there is one
          :type: :string
        :indirect_object:
          :allow_nil: true
          :description: the noun that is the indirect object of the verb if there is one
          :type: :string
      :required:
      - :language
      - :uninflected
      - :verb
  HERE
)

Foobara::Commandforge::CreateType.run!(
  organization_name: "SfRuby",
  domain_name: "AngelListMeetupDemos",
  type_name: :AnalyzedSentence,
  type_declaration: <<~HERE
    ---
    :type: :model
    :name: AnalyzedSentence
    :model_module: SfRuby::AngelListMeetupDemos
    :model_class: SfRuby::AngelListMeetupDemos::AnalyzedSentence
    :model_base_class: Foobara::Model
    :attributes_declaration:
      :type: :attributes
      :element_type_declarations:
        :original_sentence: :string
        :language: :SfRuby::AngelListMeetupDemos::language
        :corrected_sentence:
          :allow_nil: true
          :description: If the sentence has spelling errors, this will be a corrected
            version of the string
          :type: :string
        :verbs:
          :type: :array
          :element_type_declaration: :SfRuby::AngelListMeetupDemos::AnalyzedVerb
        :nouns:
          :type: :array
          :element_type_declaration: :SfRuby::AngelListMeetupDemos::AnalyzedNoun
      :required:
      - :language
      - :nouns
      - :original_sentence
      - :verbs
      :defaults:
        :verbs: []
        :nouns: []
  HERE
)

puts "Great success!!"
